name: Deploy to S3

on:
  push:
    branches:
      - main  # trigger on pushes to main branch

jobs:
  deploy:
    name: Sync Angular build to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --output-path=dist/tr-tech-client

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete   # remove --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          SOURCE_DIR: "dist/tr-tech-client"

